---
title: "Clean the Data"
author: "memrekus"
date: "6/2/2022"
output: html_document
---

__Cleaning the data from the errors__

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```


#Load Libraries


```{r}

library("data.table")
library("dplyr")
library("tidyverse")

```


#Load the Data


```{r}

Total <- readRDS("Normal_total.Rds")

```


#Cleaning


```{r}

Total$meta.sample_submitter_id<-NULL

Total$meta.submitter_id<-NULL

Total$meta.sample_type<-NULL

Total$meta.state.x<-NULL

Total$meta.ajcc_pathologic_stage.y<-NULL

Total$meta.paper_pathologic_stage<-NULL

colnames(Total)[62554]<-"meta.ajcc_pathologic_stage"

Total$meta.synchronous_malignancy.y<-NULL

colnames(Total)[62554]<-"meta.synchronous_malignancy"

Total$meta.prior_malignancy.y<-NULL

colnames(Total)[62563]<-"meta.prior_malignancy"

Total$meta.tissue_type<-NULL

Total$meta.days_to_diagnosis.y<-NULL

colnames(Total)[62555]<-"meta.days_to_diagnosis"

Total$meta.days_to_last_known_disease_status<-NULL

Total$meta.last_known_disease_status.y<-NULL

colnames(Total)[62557]<-"meta.last_known_disease_status"

Total$meta.tissue_or_organ_of_origin.y<-NULL

colnames(Total)[62558]<-"meta.tissue_or_organ_of_origin"

Total$meta.paper_days_to_last_followup<-NULL

Total$meta.days_to_last_follow_up.y<-NULL

Total$meta.days_to_last_follow_up.x<-NULL

Total$meta.age_at_diagnosis.y<-NULL

colnames(Total)[62559]<-"meta.age_at_diagnosis"

Total$meta.primary_diagnosis.y<-NULL

colnames(Total)[62560]<-"meta.primary_diagnosis"

Total$meta.year_of_diagnosis.y<-NULL

colnames(Total)[62562]<-"meta.year_of_diagnosis"

Total$meta.prior_treatment.y<-NULL

colnames(Total)[62563]<-"meta.prior_treatment"

Total$meta.ajcc_staging_system_edition.y<-NULL

colnames(Total)[62564]<-"meta.ajcc_staging_system_edition"

Total$meta.ajcc_pathologic_t.y<-NULL

colnames(Total)[62565]<-"meta.ajcc_pathologic_t"

Total$meta.morphology.y<-NULL

colnames(Total)[62566]<-"meta.morphology"

Total$meta.ajcc_pathologic_n.y<-NULL

colnames(Total)[62567]<-"meta.ajcc_pathologic_n"

Total$meta.ajcc_pathologic_n.y<-NULL

colnames(Total)[62567]<-"meta.ajcc_pathologic_n"

Total$meta.ajcc_pathologic_m.y<-NULL

colnames(Total)[62568]<-"meta.ajcc_pathologic_m"

Total$meta.classification_of_tumor.y<- NULL

colnames(Total)[62569]<-"meta.classification_of_tumor"

Total$meta.diagnosis_id.y<-NULL

colnames(Total)[62570]<-"meta.diagnosis_id"

Total$meta.icd_10_code.y<- NULL

colnames(Total)[62571]<-"meta.icd_10_code"

Total$meta.site_of_resection_or_biopsy.y<- NULL

colnames(Total)[62572]<-"meta.site_of_resection_or_biopsy"

Total$meta.Tumor_Grade<-NULL

Total$meta.paper_Tumor_Grade<-NULL

Total$meta.tumor_grade.y<-NULL

colnames(Total)[62573]<-"meta.tumor_grade"

Total$meta.alcohol_history.y<-NULL

Total$meta.alcohol_history.x<-NULL

Total$meta.alcohol_intensity<-NULL

Total$meta.progression_or_recurrence.x<-NULL

Total$meta.progression_or_recurrence.y<-NULL

Total<-Total%>%select(!(ends_with("e.y")))

Total<-Total%>%select(!(ends_with("d.y")))

Total<-Total%>%select(!(ends_with("r.y")))

Total<-Total%>%select(!(ends_with("y.y")))

Total<-Total%>%select(!(ends_with("s.y")))

Total<-Total%>%select(!(ends_with("x.y")))

Total<-Total%>%select(!(ends_with("h.y")))

Total$

colnames(Total)[62574]<-"meta.exposure_id"

colnames(Total)[62575]<-"meta.race"

colnames(Total)[62576]<-"meta.gender"

colnames(Total)[62577]<-"meta.ethnicity"

colnames(Total)[62579]<-"meta.age_at_index"

colnames(Total)[62581]<-"meta.year_of_birth"

colnames(Total)[62582]<-"meta.demographic_id"

colnames(Total)[62583]<-"meta.year_of_death"

Total$meta.bcr_patient_barcode.x<-NULL

Total$meta.paper_Tumor.Type<-NULL

Total$meta.paper_patient<-NULL

Total$meta.paper_MSI_status<-NULL

Total$meta.paper_HPV_Status<-NULL

Total$hsa.mir.423.x<-NULL

Total$hsa.mir.1253.x<-NULL

names(Total)[names(Total) == "hsa.mir.423.y"] <- "hsa.mir.423"

names(Total)[names(Total) == "hsa.mir.1253.y"] <- "hsa.mir.1253"

Total$meta.vital_status.x<-NULL

Total$meta.paper_vital_status<-NULL

Total$meta.days_to_birth<-NULL

Total$meta.paper_days_to_birth<-NULL

names(Total)[names(Total) == "meta.days_to_birth.x"] <- "meta.days_to_birth"

Total$meta.days_to_death<-NULL

Total$meta.paper_days_to_death<-NULL

names(Total)[names(Total) == "meta.days_to_death.x"] <- "meta.days_to_death"

Total$meta.paper_BRCA_Subtype_PAM50<-NULL

Total$meta.shortLetterCode<-as.factor(Total$meta.shortLetterCode)

Total$meta.definition<-as.factor(Total$meta.definition)

Total$meta.sample_type_id<-as.factor(Total$meta.sample_type_id)

Total$meta.oct_embedded<-as.logical(Total$meta.oct_embedded)

Total$meta.synchronous_malignancy<-as.factor(Total$meta.synchronous_malignancy)

Total$meta.ajcc_pathologic_stage<-as.factor(Total$meta.ajcc_pathologic_stage)

Total$meta.tissue_or_organ_of_origin<-as.factor(Total$meta.tissue_or_organ_of_origin)

Total$meta.last_known_disease_status<-NULL

Total$meta.paper_age_at_initial_pathologic_diagnosis<-NULL

Total$meta.primary_diagnosis<-as.factor(Total$meta.primary_diagnosis)

Total$meta.prior_malignancy<-as.factor(Total$meta.prior_malignancy)

Total$meta.prior_treatment<-as.factor(Total$meta.prior_treatment)

Total$meta.ajcc_staging_system_edition<-as.factor(Total$meta.ajcc_staging_system_edition)

Total$meta.ajcc_pathologic_t<-as.factor(Total$meta.ajcc_pathologic_t)

Total$meta.ajcc_pathologic_n<-as.factor(Total$meta.ajcc_pathologic_n)

Total$meta.ajcc_pathologic_m<-as.factor(Total$meta.ajcc_pathologic_m)

Total$meta.classification_of_tumor<-NULL

Total$meta.site_of_resection_or_biopsy<-NULL

Total$meta.icd_10_code<-as.factor(Total$meta.icd_10_code)

Total$meta.tumor_grade<-NULL

Total$meta.race<-as.factor(Total$meta.race)

Total$meta.gender<-as.factor(Total$meta.gender)

Total$meta.ethnicity<-as.factor(Total$meta.ethnicity)

Total$meta.vital_status<-as.factor(Total$meta.vital_status)

Total$meta.project_id<-as.factor(Total$meta.project_id)

Total$meta.name<-NULL

Total$meta.preservation_method<-as.factor(Total$meta.preservation_method)

Total$meta.days_to_sample_procurement<-NULL

Total$meta.paper_Included_in_previous_marker_papers<-NULL

Total$meta.paper_BRCA_Pathology<-NULL

Total$meta.paper_tobacco_smoking_history<-NULL

Total$meta.paper_CNV.Clusters<-NULL

Total$meta.paper_Mutation.Clusters<-NULL

Total$meta.paper_DNA.Methylation.Clusters<-NULL

Total$meta.paper_mRNA.Clusters<-NULL

Total$meta.paper_lncRNA.Clusters<-NULL

Total$meta.paper_Protein.Clusters<-NULL
  
Total$meta.paper_PARADIGM.Clusters<-NULL
  
Total$meta.paper_Pan.Gyn.Clusters<-NULL

Total$meta.Included_in_previous_marker_papers<-as.factor(Total$meta.Included_in_previous_marker_papers)

Total$meta.days_to_birth<-as.numeric(Total$meta.days_to_birth)

Total$meta.days_to_death<-as.numeric(Total$meta.days_to_death)

Total$meta.days_to_last_followup<-as.numeric(Total$meta.days_to_last_followup)

Total$meta.pathologic_stage<-as.factor(Total$meta.pathologic_stage)

Total$meta.BRCA_Pathology<-as.factor(Total$meta.BRCA_Pathology)

Total$meta.BRCA_Subtype_PAM50<-as.factor(Total$meta.BRCA_Subtype_PAM50)

Total$meta.paper_miRNA.Clusters<-NULL

Total$meta.MSI_status<-NULL

Total$meta.HPV_Status<-NULL

Total$meta.tobacco_smoking_history<-NULL

Total$meta.created_datetime<-NULL

Total$`meta.CNV Clusters`<-as.factor(Total$`meta.CNV Clusters`)

Total$`meta.Mutation Clusters`<-as.factor(Total$`meta.Mutation Clusters`)

Total$`meta.DNA.Methylation Clusters`<-as.factor(Total$`meta.DNA.Methylation Clusters`)

Total$`meta.mRNA Clusters`<-as.factor(Total$`meta.mRNA Clusters`)

Total$`meta.miRNA Clusters`<-as.factor(Total$`meta.miRNA Clusters`)

Total$`meta.lncRNA Clusters`<-as.factor(Total$`meta.lncRNA Clusters`)

Total$`meta.Protein Clusters`<-as.factor(Total$`meta.Protein Clusters`)

Total$`meta.PARADIGM Clusters`<-as.factor(Total$`meta.PARADIGM Clusters`)

Total$`meta.Pan-Gyn Clusters`<-as.factor(Total$`meta.Pan-Gyn Clusters`)

Total$meta.days_to_recurrence<-NULL

Total$meta.NA.<-NULL

Total$meta.cigarettes_per_day<-NULL

Total$meta.years_smoked<-NULL

Total$meta.treatments_pharmaceutical_days_to_treatment_end<-NULL

Total$meta.treatments_pharmaceutical_days_to_treatment_start<-NULL

Total$meta.treatments_pharmaceutical_treatment_type<-as.factor(Total$meta.treatments_pharmaceutical_treatment_type)

Total$meta.treatments_pharmaceutical_regimen_or_line_of_therapy<-NULL

Total$meta.treatments_pharmaceutical_treatment_effect<-NULL

Total$meta.treatments_pharmaceutical_therapeutic_agents<-NULL

Total$meta.treatments_pharmaceutical_treatment_or_therapy<-as.factor(Total$meta.treatments_pharmaceutical_treatment_or_therapy)

Total$meta.treatments_pharmaceutical_initial_disease_status<-NULL

Total$meta.treatments_pharmaceutical_treatment_intent_type<-NULL

Total$meta.treatments_pharmaceutical_treatment_anatomic_site<-NULL

Total$meta.treatments_pharmaceutical_treatment_outcome<-NULL

Total$meta.treatments_radiation_days_to_treatment_end<-NULL

Total$meta.treatments_radiation_days_to_treatment_start<-NULL

Total$meta.treatments_radiation_treatment_type<-as.factor(Total$meta.treatments_radiation_treatment_type)

Total$meta.treatments_radiation_regimen_or_line_of_therapy<-NULL

Total$meta.treatments_radiation_treatment_effect<-NULL

Total$meta.treatments_radiation_therapeutic_agents<-NULL

Total$meta.treatments_radiation_treatment_or_therapy<-as.factor(Total$meta.treatments_radiation_treatment_or_therapy)

Total$meta.treatments_radiation_initial_disease_status<-NULL

Total$meta.treatments_radiation_treatment_intent_type<-NULL

Total$meta.treatments_radiation_treatment_anatomic_site<-NULL

Total$meta.treatments_radiation_treatment_outcome<-NULL

```


#Save the Data 


```{r}

saveRDS(Total,file = "Total.Rds")

Total<-readRDS("Total.Rds")

```

